### ISSUE TITLE
How to set “frequence”,“q”,“gain” and other curve functions 

### ISSUE THREAD

**Issue by Kvas392** [schwinn/khtool#3]
Hi,I'm a new one for python, I want to know how to set the frequence curve functions by code, can you give examples? Thanks.

**Comment by schwinn** [comment]
Hi, 

below is an example.

These are the possible values for "type".
PARAMETRIC
LOSHELF
HISHELF
LOWPASS
HIGHPASS
BANDPASS
NOTCH
ALLPASS
HI6DB
LO6DB
INVERSION

The MA 1 software is using only using filter type "PARAMETRIC".

Hope this helps.

```
./khtool.py -i en1 -t 1 --expert '{"audio":{"out":{"equalizer":{"enabled":[true,true,true,true,true,true,true,true,true,true]}}}}'
./khtool.py -i en1 -t 1 --expert '{"audio":{"out":{"equalizer":{"type":["PARAMETRIC","PARAMETRIC","PARAMETRIC","PARAMETRIC","PARAMETRIC","PARAMETRIC","PARAMETRIC","PARAMETRIC","PARAMETRIC","PARAMETRIC"]}}}}'
./khtool.py -i en1 -t 1 --expert '{"audio":{"out":{"equalizer":{"frequency":[84.889,98.930,111.507,196.987,73.046,1291.415,135.585,55.138,381.993,583.255]}}}}'
./khtool.py -i en1 -t 1 --expert '{"audio":{"out":{"equalizer":{"q":[8.741,11.543,15.390,4.006,8.175,3.553,9.344,3.533,4.248,4.989]}}}}'
./khtool.py -i en1 -t 1 --expert '{"audio":{"out":{"equalizer":{"gain":[0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000]}}}}'
./khtool.py -i en1 -t 1 --expert '{"audio":{"out":{"equalizer":{"boost":[-3.589,-3.793,-3.041,-8.611,3.186,-2.802,-6.297,1.915,1.443,-1.265]}}}}'
```

**Comment by Kvas392** [comment]
Thanks
Can you try it in KH80dsp? (PEQ function)

**Comment by schwinn** [comment]
This will work for KH80 DSP.

**Comment by Kvas392** [comment]
Hi I try it but not work.My system is **windows11**, First I use **Powershell** to research my interface name.Then use **Miniconda3**  try to get my KH80dsp information, can you help me to find where is wrong? Follow is my code,thanks.
![image](https://github.com/schwinn/khtool/assets/154859766/7aab3476-92df-476c-bfb6-98a76a883537)

---------------------------------------------------------------------------------------------------------------------------------
PS C:\Users\Mazhe> ipconfig
Windows IP Configuration
Ethernet adapter 以太网 6:
 Media State . . . . . . . . . . . : Media disconnected
Connection-specific DNS Suffix  . :
Wireless LAN adapter WLAN 2:
Connection-specific DNS Suffix  . :
   IPv6 Address. . . . . . . . . . . : 2409:8a18:c16:xxxx::xxx
   IPv6 Address. . . . . . . . . . . : 2409:8a18:c16:c290:100e:9796:xxxx:xxxx
   Temporary IPv6 Address. . . . . . : 2409:8a18:c16:c290:80dc:1a9f:xxxx:xxxx
   Link-local IPv6 Address . . . . . : fe80::f3ef:4856:447b:63xxxx
   IPv4 Address. . . . . . . . . . . : 192.168.xxx.x
   Subnet Mask . . . . . . . . . . . : 255.255.xxx.x
   Default Gateway . . . . . . . . . : fe80::12xxx
                                       192.168.xxxx.x
-------------------------------------------------------------------------------------------
(base) PS C:\Users\Mazhe> cd D:\khtool-main\
(base) PS D:\khtool-main> python .\khtool.py
usage: khtool.py [-h] [--scan] [-q] [--backup BACKUP] [--restore RESTORE] [--comment COMMENT] [--save]
                 [--brightness BRIGHTNESS] [--delay DELAY] [--dimm DIMM] [--level LEVEL] [--mute] [--unmute]
                 [--expert EXPERT] -i INTERFACE [-t {all,0,1,2,3,4,5,6,7,8}] [-v]
khtool.py: error: the following arguments are required: -i/--interface
(base) PS D:\khtool-main> python .\khtool.py -i WLAN2 -q
Traceback (most recent call last):
  File "D:\khtool-main\khtool.py", line 537, in <module>
    main()
  File "D:\khtool-main\khtool.py", line 530, in main
    device.connect(interface=interface)
  File "C:\Users\Mazhe\AppData\Roaming\Python\Python311\site-packages\pyssc\Ssc_device.py", line 29, in connect
    self.socket = socket.create_connection((self.ip + interface, port))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo

**Comment by schwinn** [comment]
I have never tested it on Windows. I will test it in the next few days and get back to you.

**Comment by Kvas392** [comment]
Thanks,I connect right speaker to my PC **with actual net line**, I also try it with **CMD**, Now I can generate **khtool.json**, **json's information is right ,but order(-q) don't work.**
-----------------------------------------------------------------------------------------------------------
Microsoft Windows [Version 10.0.22631.2861]
(c) Microsoft Corporation. All rights reserved.

D:\khtool-main>python .\khtool.py
usage: khtool.py [-h] [--scan] [-q] [--backup BACKUP] [--restore RESTORE] [--comment COMMENT] [--save]
                 [--brightness BRIGHTNESS] [--delay DELAY] [--dimm DIMM] [--level LEVEL] [--mute] [--unmute]
                 [--expert EXPERT] -i INTERFACE [-t {all,0,1,2,3,4,5,6,7,8}] [-v]
khtool.py: error: the following arguments are required: -i/--interface

D:\khtool-main>python .\khtool.py -i\--Ethernet6\-q
Found 1 Device(s) and stored configuration to khtool.json.
![image](https://github.com/schwinn/khtool/assets/154859766/7cf16d03-8815-45b8-b000-54b0c0d12809)

![image](https://github.com/schwinn/khtool/assets/154859766/feae8bb7-07a1-4557-b7e3-051cd4402a6b)

**Comment by schwinn** [comment]
If you have two sepakers connected, please use this command, until both speakers are discovered.

`D:\khtool-main>python .\khtool.py -i Ethernet6 --scan`

The you can use this command the query all speakers.

`D:\khtool-main>python .\khtool.py -i Ethernet6 -q`

**Comment by Kvas392** [comment]
Hi, I try it and find my two speakers, but it show the Errno 11001 ,I will search further on Google, and wait for your test, Thanks.
![image](https://github.com/schwinn/khtool/assets/154859766/842f2298-806c-4970-ae7d-d8a86893eb33)
![image](https://github.com/schwinn/khtool/assets/154859766/28abfc4b-3981-4210-b48b-82f39d004489)

**Comment by schwinn** [comment]
I have uploaded a new version. Please give it a try. Under windows, the inteface no longer needs to be specified.

**Comment by Kvas392** [comment]
**_Best wishes for a happy  New Year!_**
I test it in win11, but I find some issue in it:
1. the equalizer can't show all parameters(**like q gain and other frequency...** );
![image](https://github.com/schwinn/khtool/assets/154859766/9e4ab5f3-8b81-405b-b853-2d2966f04d22)
2. the expert mode seem not work;
![image](https://github.com/schwinn/khtool/assets/154859766/f193ab2c-b389-4f40-9db7-2c72e2946519)
----
**Brightness/Mute/Unmute/Save is work.**

**Comment by schwinn** [comment]
Hi,

I have reverted the last change in khtool. The interface must now specified again. On my Windows 11 system, I did a ipconfig /all and the local link IPv6 address of the adapter was like 'fe80::3000:0000:0000:cd4f%35'. Then the interface name is the name after the percent sign, so it's 35 in this case.

On windows, the quotation marks has to be excaped. So the correct expert mode command looks like this:

`python khtool.py -i 35 --expert {\"m\":{\"audio\":null}} -t 0`

The problem with the incomplete output is related to the pyssc library. Please use the my fork of the library. Here are the commands to replace the version.

```
pip3 uninstall pyssc
pip3 install https://github.com/schwinn/pyssc/archive/master.zip#egg=pyssc
```

**Comment by Kvas392** [comment]
Hi 
It not ok
Step1:
I connect my Right speaker to motherboard with line, I can find it in MA1 sofaware
![image](https://github.com/schwinn/khtool/assets/154859766/5d215a28-20b3-4052-b63a-15212ddb8c98)
![image](https://github.com/schwinn/khtool/assets/154859766/bdea608e-18ef-4701-88b7-3e659ba353c4)
I also try Left speaker, It work.
![image](https://github.com/schwinn/khtool/assets/154859766/87e31231-5fe3-4ca1-803a-9a6a08a78c36)
Step2:
I research 以太网6 Idx with CMD, the Idx is 4
![image](https://github.com/schwinn/khtool/assets/154859766/e0d5d478-cb63-4604-8380-ff086e34e4c7)
Step3:
I exit MA1 software, and try khtool.py but not work.
![image](https://github.com/schwinn/khtool/assets/154859766/5ec0d674-6d9e-4ab8-ba84-e0e8cc3c3145)
Step4:
I check 以太网6 IPv6，not find problem
![image](https://github.com/schwinn/khtool/assets/154859766/5e42834c-cd8f-4514-a44a-9ceb6a7e0eb8)
![image](https://github.com/schwinn/khtool/assets/154859766/dc105feb-e41c-4982-98c8-b8c5dfff9b4b)
PS:
I connect pair speakers to my H3C BX54 Router LAN ,and try to find them on WIFI with MA1 software, I can't see anyone, I will try to check my setting ,strangeness......
![image](https://github.com/schwinn/khtool/assets/154859766/eb8353dd-be09-4e24-84db-510225a61243)
![image](https://github.com/schwinn/khtool/assets/154859766/dcd14e0b-bd6f-4b9c-8dbc-809ebc8c08a9)

**Comment by Kvas392** [comment]
I restart my PC,  Open MA1 Software, I can find pair speakers use WIFI(WLAN2), then try khtool.py  it also not find my speakers.
![image](https://github.com/schwinn/khtool/assets/154859766/f54a34ce-3904-420b-a078-64e906c229b7)
![image](https://github.com/schwinn/khtool/assets/154859766/17931588-7031-4c1d-b35c-7f374aad105c)
![image](https://github.com/schwinn/khtool/assets/154859766/36536f25-814f-432c-b9e6-9e83c356d50e)

**Comment by schwinn** [comment]
This is strange, because the interface configuration is not used for the device scanning. I have uploaded a new version, where the scanning timeout is increased. Please power cycle your speakers before the scan and try the new version.

**Comment by schwinn** [comment]
Please post the output of `pip3 show pyssc`

**Comment by Kvas392** [comment]
Hi update new khtool and this is my test,but have some problems：
Step1：get the pyssc information
![image](https://github.com/schwinn/khtool/assets/154859766/6cf6d1fa-e497-4702-a545-19414cc365eb)
Step2:  use MA1 software to find speakers by WLAN2, it ok
![image](https://github.com/schwinn/khtool/assets/154859766/3f6227a4-f0c2-48f9-86ac-ac3f01005fe6)
Step3: research WLAN2 Idx ,Idx=9
![image](https://github.com/schwinn/khtool/assets/154859766/110ae919-e949-41f9-ae68-b0dd477e48c0)
Step4: try to find my pair speakers by khtool, it can find pair speakers and creative the json
![image](https://github.com/schwinn/khtool/assets/154859766/3c01919f-a0d1-49d6-bfbd-c0d95cace67a)
![image](https://github.com/schwinn/khtool/assets/154859766/68d41e6a-605b-4c7a-b3fc-ea3704278fe7)
Step5: try to get the pair speakers informations, but it show my Front Left not online,also no Right information
![image](https://github.com/schwinn/khtool/assets/154859766/bf1aa70f-5a09-426d-a088-23a419c6e1dd)
Step5: Try searching for speakers again，it also can find speakers
![image](https://github.com/schwinn/khtool/assets/154859766/aaca3d42-ec95-4432-b43a-5bd87e561502)

**Comment by Kvas392** [comment]
Hi I test the last version, All functions are working and successful, I will buy a pair of KH120II later and test it.
The Ipv6 address seems beacause of in China and use wifi to connect my speakers
Very Thanks for you. 
![image](https://github.com/schwinn/khtool/assets/154859766/07f960b8-3513-4328-8cd4-e9850e8b89d0)
